kind: Service
apiVersion: apiVersion=v1
metadata:
  name: notesApp
  namespace: euc-ns
spec:
  selector:
    app: notesApp
  ports:
  - protocol: TCP
    port: 8080
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notesApp
  namespace: euc-ns
spec:
  selector:
      matchLabels:
        app: notesApp
  replicas: 2
  template:
    metadata:
      labels:
        app: notesApp
    spec:
      containers:
        - name: notesApp
          image: venkatadri/springboot-notesapp
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
