
apiVersion: v1
kind: Namespace
metadata:
  name: euc-ns
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: euc-ns
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
     # Which port on the node is the service available through?
  - nodePort: 31234
    name: mysql
  clusterIP: None
  selector:
    app: mysql
   
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql
  namespace: euc-ns
spec:
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.6
        env:
          # Use secret in real usage
        - name: root
          value: root
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
    name: mysql-vol
    annotations:
      volume.beta.kubernetes.io/storage-class: portworx-repl-2
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
